### ISSUE TITLE
Unagi is breaking WooCommerce home page

### ISSUE THREAD

**Issue by sanzeeb3** [HandyPlugins/unagi#2]
Unagi is creating issues with WC homepage: wp-admin/admin.php?page=wc-admin. The contents of the page slide down to the right.

**Comment by sanzeeb3** [comment]
Probably, screen ID can be checked here for both homepage and setup wizard: https://github.com/HandyPlugins/unagi/blob/main/includes/shovel.php#L103

Something like: 

```
$screen    = get_current_screen();

/**
* Dirty way to make it work with WooCommerce setup wizard
* It is what it is!!!...
*/
if ( isset( $screen->id ) && $screen->id === 'woocommerce_page_wc-admin' ) {
    $is_shoveling = false;
}
```

**Comment by mustafauysal** [comment]
Hi @sanzeeb3,

Thanks for the report, I will check this. I guess the screen is not ready on the setup wizard, we might check query strings only.

**Comment by mustafauysal** [comment]
@sanzeeb3 fixed in version 0.1.1

**Comment by sanzeeb3** [comment]
@mustafauysal I think with this change, there are a lot of warnings and eventually, the plugin is unusable.

**Comment by mustafauysal** [comment]
@sanzeeb3 can you give a bit more details about the warning?

**Comment by sanzeeb3** [comment]
@mustafauysal - it looks like the issue isn't reproducible - that is probably only under certain conditions. AFAIR, it was a warning about 'headers already sent' on every page load.

**Comment by mustafauysal** [comment]
I don't see any problem with my dev environment with Woo, there might be some conflict with other plugins.
I'm closing this issue, but feel free to reopen it if you can get reproduce it.

Thanks,

**Comment by sanzeeb3** [comment]
@mustafauysal Are you also not facing issues with WooCommerce dashboard widget? I can check to reproduce the issue, though.

**Comment by sanzeeb3** [comment]
It May not be directly related to the issue I was facing, [this user ](https://wordpress.org/support/topic/rev-slider-plugin-crash-plugin/#post-14287597) also has issues with 0.1.1, and reverting to 0.1.0 fixed the problem.

**Comment by mustafauysal** [comment]
> Are you also not facing issues with WooCommerce dashboard widget? 

Nope, I didn't see anything wrong with a clean install. 

> It May not be directly related to the issue I was facing, this user also has issues with 0.1.1, and reverting to 0.1.0 fixed the problem.

I think this is causing when a plugin adds js with `admin_notice` hook.

**Comment by mustafauysal** [comment]
@sanzeeb3 I've added screen checking in version 0.1.2.  7bfa904c302f54bee8884502cf66d4b6d790b77c along with better js/css handling. I hope it fixes the problem.

I'm closing this issue again, feel free to re-open if the problem persists.

**Comment by sanzeeb3** [comment]
@mustafauysal - Thanks for the improvements. With the change, It looks like the notifications still appear on other pages of WC such as Reports, Settings, etc.

**Comment by sanzeeb3** [comment]
Also, on the Orders page, there is a huge gap (https://a.supportally.com/1TErgd) probably meant for notices that aren't there.
