### ISSUE TITLE
Add heading to the 'Notifications' page

### ISSUE THREAD

**Issue by sanzeeb3** [HandyPlugins/unagi#3]
Currently, the Notifications page lacks a heading.  All the WP pages such as Plugins, Settings, Tools, Users, etc. have headings. So, a 'Notifications' heading on the notifications page is expected.

![Screenshot on 2021-04-05 at 20_47_16](https://user-images.githubusercontent.com/16817248/113589052-a2ee2c00-9650-11eb-9363-e5a9a6b4a545.png)

**Comment by mustafauysal** [comment]
Hi @sanzeeb3, 

I left a few feedback to your PR, could you update? Also, that would be better to target develop branches instead of main. (I should write these to PR template) :)

**Comment by mustafauysal** [comment]
Merged in version 0.1.2!

Thanks, @sanzeeb3
